export const models = [
  { id: 'ape', title: 'Realistic Ape', description: 'Rigged Blender character with detailed fur, PBR materials, and a render-ready scene.', url: 'https://superhivemarket.com/products/realistic-ape--rigged-3d-character-for-blender' },
  { id: 'beetle', title: 'Classic VW Beetle', description: 'Rigged wheels and suspension, PBR textures, and an organized Blender scene at real-world scale.', url: 'https://superhivemarket.com/products/classic-vw-beetle-3d-model--high-quality-game--render-ready' },
  { id: 'trolley', title: 'Portuguese Vintage Trolley', description: 'Porto and Lisbon-inspired streetcar with weathered textures and 4K PBR maps. Includes Blend, FBX, and OBJ files.', url: 'https://superhivemarket.com/products/portuguese-vintage-trolley--portolisbon-style-3d-model' },
];
export type MakingOfPost = { title: string; type: string; image?: string; url: string };
export const makingOf: MakingOfPost[] = [
  { title: 'Text Effect', type: 'Geometry Nodes tutorial', image: '/work/b5fd6b535097233b.jpg', url: 'https://www.patreon.com/PlugIn3D/posts/text-effect-in-1-167470462' },
  { title: 'Fighter Jet', type: 'Animation & water-drop trails', image: '/projects/figtherjet-1-small.webp', url: 'https://www.patreon.com/PlugIn3D/posts/fighter-jet-geo-161534273' },
  { title: 'Tree Man', type: 'Procedural character tutorial', image: '/projects/treeman-1-small.webp', url: 'https://www.patreon.com/PlugIn3D/posts/treeman-from-158604585' },
  { title: 'Head Splitting', type: 'Geometry Nodes effect', image: '/work/79c0eaa4c98a0f34.jpg', url: 'https://www.patreon.com/PlugIn3D/posts/head-splitting-155617782' },
  { title: 'Head Through Bars', type: 'Geometry Nodes tutorial', image: '/making-of/155503335.webp', url: 'https://www.patreon.com/PlugIn3D/posts/head-through-geo-155503335' },
  { title: 'Ring Particles', type: 'Particle effect tutorial', image: '/projects/ring-2-small.webp', url: 'https://www.patreon.com/PlugIn3D/posts/ring-particle-155035269' },
  { title: 'Camera Autofocus', type: 'Geometry Nodes setup', image: '/making-of/149929516.webp', url: 'https://www.patreon.com/PlugIn3D/posts/camera-autofocus-149929516' },
  { title: 'Coffee Bean Exploding Effect', type: 'Geometry Nodes tutorial', image: '/work/2d20d4e0fce49c88.jpg', url: 'https://www.patreon.com/PlugIn3D/posts/coffee-bean-in-151559804' },
  {"title":"Tree Man Environment","type":"Environment breakdown","image":"/making-of/159567319.webp","url":"https://www.patreon.com/PlugIn3D/posts/look-on-how-i-in-159567319"},
  {"title":"Snow Stepping","type":"Geometry Nodes effect","image":"/making-of/150135196.webp","url":"https://www.patreon.com/PlugIn3D/posts/snow-stepping-on-150135196"},
  {"title":"Watch Assembling","type":"Geometry Nodes project","image":"/making-of/148958534.webp","url":"https://www.patreon.com/PlugIn3D/posts/watch-assembling-148958534"},
  {"title":"Portrait Cloth","type":"Cloth effect project","image":"/making-of/147739851.webp","url":"https://www.patreon.com/PlugIn3D/posts/portrait-cloth-147739851"},
  {"title":"Zipper Looping","type":"Geometry Nodes project","image":"/making-of/144846539.webp","url":"https://www.patreon.com/PlugIn3D/posts/zipper-looping-144846539"},
  {"title":"Tree Growing","type":"Geometry Nodes effect","image":"/making-of/144846427.webp","url":"https://www.patreon.com/PlugIn3D/posts/tree-growing-in-144846427"},
  {"title":"Procedural Starfish","type":"Geometry Nodes project","image":"/making-of/144846197.webp","url":"https://www.patreon.com/PlugIn3D/posts/procedural-geo-144846197"},
  {"title":"Spike Ice","type":"Geometry Nodes project","image":"/making-of/144845221.webp","url":"https://www.patreon.com/PlugIn3D/posts/spike-ice-geo-144845221"},
  {"title":"Procedural Ring","type":"Project & tutorial","image":"/making-of/144841761.webp","url":"https://www.patreon.com/PlugIn3D/posts/procedural-ring-144841761"},
  {"title":"Paper Burn","type":"Project & tutorial","image":"/making-of/144841062.webp","url":"https://www.patreon.com/PlugIn3D/posts/paper-burn-in-w-144841062"},
  {"title":"Bee Hive","type":"Project & tutorial","image":"/making-of/144840746.webp","url":"https://www.patreon.com/PlugIn3D/posts/bee-hive-in-geo-144840746"},
  {"title":"Halloween House","type":"Project & tutorial","image":"/making-of/144840626.webp","url":"https://www.patreon.com/PlugIn3D/posts/procedural-house-144840626"},
  {"title":"Gummy Simulation","type":"Project & tutorial","image":"/making-of/144840525.webp","url":"https://www.patreon.com/PlugIn3D/posts/gummy-simulation-144840525"},
  {"title":"Procedural Donut","type":"Geometry Nodes project","image":"/making-of/144840040.webp","url":"https://www.patreon.com/PlugIn3D/posts/blender-donut-in-144840040"},
  {"title":"Bouquet","type":"Geometry Nodes project","image":"/making-of/144839937.webp","url":"https://www.patreon.com/PlugIn3D/posts/bouquet-geo-file-144839937"},
  {"title":"Audience Count","type":"Project & tutorial","image":"/making-of/144839753.webp","url":"https://www.patreon.com/PlugIn3D/posts/audience-count-w-144839753"},
];
